apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-api
  template:
    metadata:
      labels:
        app: echo-api
    spec:
      containers:
      - name: app
        image: ghcr.io/romgzn/echo-api:latest
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
          - configMapRef:
              name: echo-api-config
          - secretRef:
              name: echo-api-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5